collated: true
default: topic
variants:
- name: topic
  context:
    id: business
    title: "[Business](/topic/business/)"
    icon: topic-business
    mods: [topic]
    content: |
      Where there's muck, there are clients, deliverables and contracts. Occasionally, there's brass. Here are articles on developing and improving relationships with clients; managing projects, both business and personal; writing contracts and presenting your work; and encouraging success and avoiding failure.
- name: archive
  context:
    id: 2013
    title: "[2013](/2013/)"
    content: |
      Scourge of browser vendors everywhere, WaSP buzzed its last in March. Dave Shea's CSS Zen Garden celebrated its tenth anniversary in May, and Google Glass was released. Ever broad in its interests, 24 ways tamed Grunt, URLs and GitHub Pages, encouraged readers to write and publish books, and leavened all that with goodies on project management, web typography and SVG.
- name: sponsor
  context:
    id: sponsor
    title: "Brought to you by"
    mods: [sponsor]
    component: promo
- name: authors
  context:
    id: a
    title: "A"
    component: authors-list
    config:
      authors:
      - John Allsopp
      - Rachel Andrew
      - Paul Annett
