collated: true
default: topic
variants:
- name: topic
  context:
    id: business
    title: "[Business](/topic/business/)"
    icon: topic-business
    mods: [topic]
    content: |
      Where there's muck, there are clients, deliverables and contracts. Occasionally, there's brass. Here are articles on developing and improving relationships with clients; managing projects, both business and personal; writing contracts and presenting your work; and encouraging success and avoiding failure.
- name: archive
  context:
    id: 2013
    title: "[2013](/2013/)"
    content: |
      Scourge of browser vendors everywhere, WaSP buzzed its last in March. Dave Shea's CSS Zen Garden celebrated its tenth anniversary in May, and Google Glass was released. Ever broad in its interests, 24 ways tamed Grunt, URLs and GitHub Pages, encouraged readers to write and publish books, and leavened all that with goodies on project management, web typography and SVG.
- name: author
  context:
    id: author
    title: "About the author"
    content: |
      Drew McLellan is lead developer on your favourite content management systems, [Perch and Perch Runway](https://grabaperch.com/). He is Director and Senior Developer at edgeofmyseat.com in Bristol, England, and is formerly Group Lead at the Web Standards Project. When not publishing 24 ways, Drew keeps a [personal site](http://allinthehead.com/) covering web development issues and themes, [takes photos](http://flickr.com/drewm/), [tweets a lot](http://twitter.com/drewm) and tries to stay upright on his bicycle.

      <span class="photo-credit">Photo: [James Duncan Davidson](http://duncandavidson.com/)</span>

      <a class="c-continue" href="/authors/drewmclellan/">More articles by Drew</a>
- name: sponsor
  context:
    id: sponsor
    title: "Brought to you&nbsp;by"
    mods: [sponsor]
    component: promo
- name: comments
  context:
    id: comments
    title: "Comments"
    content: |
      <a class="c-continue" href="/YYYY/article-slug/comments" data-replace data-interaction data-target="#comments">View 11 readers’ comments</a>
- name: related
  context:
    id: related
    title: "Related articles"
    mods: [related]
    component: grid--ways
- name: authors
  context:
    id: a
    title: "A"
    component: grid--authors
    config:
      mods: [authors]
      component: author
      items:
      - author: John Allsopp
      - author: Rachel Andrew
      - author: Paul Annett
- name: loading
  context:
    id: loading
    title: "Loading"
    mods: [loading]
    component: activity
