context:
  title: "2013"
  content: |
    <cite>24 ways</cite> is the advent calendar for web geeks. Each day throughout December we publish a daily dose of web design and development goodness to bring you all a little Christmas cheer. [Learn more](/pages/about/)
  section: home
  theme: year-2013
