context:
  title: "2013"
  content: |
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse feugiat, elit nec malesuada interdum, nibh erat convallis turpis, vel mollis mi sem ac arcu.
  section: archives
  theme: year-2013
  traverse:
    type: archive
    prev:
      url: /2012/
      title: "2012"
    next:
      url: /2014/
      title: "2014"
