context:
  title: "Authors"
  section: authors
  sections:
  - id: a
    title: "A"
    component: authors-list
    config:
      authors:
      - John Allsopp
      - Rachel Andrew
      - Paul Annett
  - id: b
    title: "B"
    component: authors-list
    config:
      authors:
      - Ashley Baxter
      - Darren Beale
      - Gavin Bell
      - Frances Berriman
      - Kimberly Blessing
      - Paul Boag
      - Ben Bodien
      - Jina Bolton
      - Mark Boulton
      - Cennydd Bowles
      - Ross Bruniges
      - Andy Budd
      - Heather Burns
  - id: c
    title: "C"
    component: authors-list
    config:
      authors:
      - Dan Cederholm
      - Andy Clarke
      - Geri Coady
      - Dave Collins
      - Simon Collison
      - Rebecca Cottrell
      - Chris Coyier
      - Matt Curry
