context:
  title: "404"
  section: about
  sections:
  - id: error
    title: Page not found
    lede: Sorry, but we can't find that page.
    content: |
      The page you requested wasn't found in the location specified. You may have an incorrect URL, or the file could have been moved or renamed.

      If you're having problems finding a particular page, try searching the site or return to the homepage.
  - id: search
    title: Search 24 ways
    component: search-form
