context:
  title: "Archives"
  section: archives
  sections:
  - id: 2015
    title: "[2015](/2015/)"
    content: |
      Ports and protocols were the name of the game, with swathes of the web switching to HTTPS connections. HTTP2 also started to gain adoption, and in doing so turned all we had learned about performance optimisation on its head. 24 ways saw increasing exploration of animation on the web, as well as renewed interest in accessibility, style guides and progressive enhancement.
  - id: 2014
    title: "[2014](/2014/)"
    content: |
      The web turned twenty-five and showed no sign of settling down in semi-detached suburbia. In October, HTML5 was released as a W3C Recommendation. Back in May, 24 ways was very excited and grateful to win the net award for best collaborative project – a huge thank you to all our authors, readers and supporters!
  - id: 2013
    title: "[2013](/2013/)"
    content: |
      Scourge of browser vendors everywhere, WaSP buzzed its last in March. Dave Shea's CSS Zen Garden celebrated its tenth anniversary in May, and Google Glass was released. Ever broad in its interests, 24 ways tamed Grunt, URLs and GitHub Pages, encouraged readers to write and publish books, and leavened all that with goodies on project management, web typography and SVG.
  - id: 2012
    title: "[2012](/2012/)"
    content: |
      During the same month that HTML5 was designated a Candidate Recommendation by the W3C, 24 ways covered issues of performance as part of responsive web design, CSS and preprocessing, responsive images (again) and design systems.
  - id: 2011
    title: "[2011](/2011/)"
    content: |
      In October, Steve Jobs died. The thorniest part of responsive web design, and an arena for many competing and dissenting voices was images. 24 ways tackled that and many other issues head on: conditional loading; front-end style guides; icon fonts; and the importance of side projects.
  - id: 2010
    title: "[2010](/2010/)"
    content: |
      In April, the iPad; in May, Ethan Marcotte's "Responsive Web Design" was published by A List Apart, and A Book Apart published <cite>HTML5 for Web Designers</cite> by Jeremy Keith; and then in June, the iPhone 4's Retina screen changed the web development landscape. 24 ways sprinkled its Christmas pudding with CSS3, including animations and transforms, a little light content strategy, and some thoughts about the web designer of tomorrow.
  - id: 2009
    title: "[2009](/2009/)"
    content: |
      A year when books were winning (Five Simple Steps published <cite>A Practical Guide to Designing for the Web</cite> by Mark Boulton and <cite>Designing with Web Standards</cite> by Jeffrey Zeldman and Ethan Marcotte reached its third edition) and the web was losing (Yahoo! closed Geocities). Significant progress was made with web fonts and HTML5, and 24 ways delivered the Christmas gifts again.
  - id: 2008
    title: "[2008](/2008/)"
    content: |
      This year saw Apple's App Store open, and the release of Android 1.0 and Google Chrome 1.0. Taking all that in its stride, 24 ways brought its seasonal perspective to bear on business, with articles on project management, the path from design to development, how to charm clients, and killer contracts. Also, a first look at modular layout systems. Pulse, meet finger.
  - id: 2007
    title: "[2007](/2007/)"
    content: |
      Apple launched the iPhone in June; Amazon released the Kindle in November — a big year. At three, 24 ways was as diverse as ever, taking a detailed look at font stacks, website performance, working with clients and markup.
  - id: 2006
    title: "[2006](/2006/)"
    content: |
      In March, the first tweets were tweeted; in August, jQuery 1.0 appeared. In its second year, 24 ways wrote responsible JavaScript and hinted at a mobile web, although mobile phones didn't yet have proper browsers. Using CSS3 in client work was still a pipedream. And in October, IE7 was officially released by Microsoft — no words.
  - id: 2005
    title: "[2005](/2005/)"
    content: |
      It all started here, in the heady days of Web 2.0. Ajax was the first new browser technology we'd seen in years, and combined with a new breed of libraries such as Prototype, it kick-started the JavaScript renaissance.
