default: ways
variants:
- name: ways
  context:
    mods: [ways]
    component: summary
    items:
    - "@summary"
    - "@summary"
    - "@summary"
    - "@summary"
    - "@summary"
    - "@summary"
    - "@summary"
    - "@summary"
    - "@summary"
    - "@summary"
    - "@summary"
- name: authors
  context:
    mods: [authors]
    component: author
    items:
    - author: Drew McLellan
    - author: Brian Suda
    - author: Anna Debenham
    - author: Owen Gregory
