context:
  title: "Starting Your HTML5 Project on the Right Foot (and Keeping It There)"
  content: |
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse feugiat, elit nec malesuada interdum, nibh erat convallis turpis, vel mollis mi sem ac arcu.
  section: article
  theme: year-2013
  traverse:
    type: article
    prev:
      url: /2015/how-tabs-should-work/
      title: "How Tabs Should Work"
    next:
      url: /2015/solve-the-hard-problems/
      title: "Solve the Hard Problems"
